/* Generated code */

interface TokenInfo {

	/**
	 * Access token to pass to subsequent API requests
	 */
	access_token?: string;

	/**
	 * Issued access token TTL (time to live), in seconds
	 */
	expires_in?: number;

	/**
	 * Refresh token to get a new access token, when the issued one expires
	 */
	refresh_token?: string;

	/**
	 * Issued refresh token TTL (time to live), in seconds
	 */
	refresh_token_expires_in?: number;

	/**
	 * List of permissions allowed with this access token, white-space separated
	 */
	scope?: string;

	/**
	 * Type of token. Use this parameter in Authorization header of requests
	 */
	token_type?: string;

	/**
	 * Extension identifier
	 */
	owner_id?: string;

	/**
	 * Unique identifier of a client application passed by the client, or auto-generated by server if not specified in request
	 */
	endpoint_id?: string;
}

export default TokenInfo;
